#!/bin/bash

mkdir /tmp/hi
mkdir /tmp/h1/1
touch /tmp/hi/1/test\ file.txt

updatedb
searchpattern=$1
results=$(locate "$searchpattern")

if [ "$results" = "" ] 
then
	echo "The results of locate do not exist"
elif [ "$results" != "" ]
then
	echo "The results of locate are below:"
	echo "$results"
	while true ; do
		read -rp "Is this what you are looking for? " yn
		case "$yn" in
			[Yy]*)
				exit 0
			;;
			[Nn]*)
				break
			;;
			*)
				echo "Please enter yes or no: "
			;;
		esac
	done	
fi

search() {
	#$1=search criteria
	ls -laR | grep "$1"
}
while true; do
dirarray=$(ls -a)
for ((i=0; i<"${#dirarray[@]}"; i++)); do
	if [ -d "${dirarray[i]}" ]; then
		cd "${dirarray[i]}" || exit
		echo "in new dir"
		search "$searchpattern"
		while true ; do
			read -rp "Is this what you are looking for? " yn
			case $yn in
				[Yy]*)  break;;
				[Nn]*)  cd ..;
						break;;
				*) echo "Please enter yes or no ";;
			esac
		done
	else 
		echo "in else part"
	fi
done
done
